- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
- coords:
  - 0
  - 0
  - 0
  marker: false
