controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

joint_group_velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3

    command_interfaces:
      - velocity

    state_interfaces:
      - velocity
      - effort